'use strict';

const SOUNDS = [
    { id: 'bicycle', name: 'Bicycle' },
    { id: 'car', name: 'Car' },
    { id: 'cash', name: 'Cash' },
    { id: 'cat', name: 'Cat' },
    { id: 'dog', name: 'Dog 1' },
    { id: 'dog2', name: 'Dog 2' },
    { id: 'energy', name: 'Energy' },
    { id: 'knock-knock', name: 'Knock Knock' },
    { id: 'letter_email', name: 'Letter Email' },
    { id: 'lose1', name: 'Lose 1' },
    { id: 'lose2', name: 'Lose 2' },
    { id: 'negative1', name: 'Negative 1' },
    { id: 'negative2', name: 'Negative 2' },
    { id: 'negative3', name: 'Negative 3' },
    { id: 'negative4', name: 'Negative 4' },
    { id: 'negative5', name: 'Negative 5' },
    { id: 'notification', name: 'Notification 1' },
    { id: 'notification2', name: 'Notification 2' },
    { id: 'notification3', name: 'Notification 3' },
    { id: 'notification4', name: 'Notification 4' },
    { id: 'open_door', name: 'Open Door' },
    { id: 'positive1', name: 'Positive 1' },
    { id: 'positive2', name: 'Positive 2' },
    { id: 'positive3', name: 'Positive 3' },
    { id: 'positive4', name: 'Positive 4' },
    { id: 'positive5', name: 'Positive 5' },
    { id: 'positive6', name: 'Positive 6' },
    { id: 'statistic', name: 'Statistic' },
    { id: 'thunder', name: 'Thunder' },
    { id: 'water1', name: 'Water 1' },
    { id: 'water2', name: 'Water 2' },
    { id: 'win', name: 'Win 1' },
    { id: 'win2', name: 'Win 2' },
    { id: 'wind', name: 'Wind long' },
    { id: 'wind_short', name: 'Wind short' },
    { id: 'alarm1', name: 'Alarm 1' },
    { id: 'alarm2', name: 'Alarm 2' },
    { id: 'alarm3', name: 'Alarm 3' },
    { id: 'alarm4', name: 'Alarm 4' },
    { id: 'alarm5', name: 'Alarm 5' },
    { id: 'alarm6', name: 'Alarm 6' },
    { id: 'alarm7', name: 'Alarm 7' },
    { id: 'alarm8', name: 'Alarm 8' },
    { id: 'alarm9', name: 'Alarm 9' },
    { id: 'alarm10', name: 'Alarm 10' },
    { id: 'alarm11', name: 'Alarm 11' },
    { id: 'alarm12', name: 'Alarm 12' },
    { id: 'alarm13', name: 'Alarm 13' },
]

module.exports = {
    SOUNDS: SOUNDS
};

